#Carregando Bibliotecas

library(readr)
library(dplyr)
library(SparseM)
library(mice)
library(mlbench)
library(e1071)
library(Amelia)
library(corrplot)
library(caret)
library(rpart)
library(rpart.plot)
library(VIM)
library(randomForest)
library(psych)
library(class)
library(ROSE)
library(DMwR)
library(caretEnsemble)
library(kernlab)
library(Boruta)
library(doParallel)

source("preprocessamento.R")
source("correlacao.R")
source("rfe.R")
source("tree.R")
source("ensemble.R")
source("boruta.R")
source("bayes.R")
source("knn.R")
source("randomforest.R")
source("ensemble.R")



